import React from 'react';
import { useParams } from 'react-router-dom';
var carDetails = {
    1: {
        manufacturer: 'BMW',
        model: '5 Series',
        year: 2018,
        fuelType: 'Petrol',
        engineCapacity: '3000cc',
        transmission: 'Automatic',
        seatingCapacity: 5,
        color: 'Gray',
        features: 'Powerful engine, Luxurious interior',
    },
    2: {
        manufacturer: 'Audi',
        model: 'Q8',
        year: 2017,
        fuelType: 'Petrol',
        engineCapacity: '4000cc',
        transmission: 'Automatic',
        seatingCapacity: 5,
        color: 'Black',
        features: 'Advanced safety features, High performance',
    },
    3: {
        manufacturer: 'Toyota',
        model: 'Camry',
        year: 2019,
        fuelType: 'Hybrid',
        engineCapacity: '2500cc',
        transmission: 'Automatic',
        seatingCapacity: 5,
        color: 'White',
        features: 'Fuel-efficient, Reliable',
    },
    4: {
        manufacturer: 'Cadillac ',
        model: 'Escallade',
        year: 2020,
        fuelType: 'Petrol',
        engineCapacity: '2400cc',
        transmission: 'Automatic',
        seatingCapacity: 5,
        color: 'Blue',
        features: 'Comfortable, Advanced technology',
    },
    5: {
        manufacturer: 'Mercedes-Benz',
        model: 'C-Class',
        year: 2019,
        fuelType: 'Diesel',
        engineCapacity: '2000cc',
        transmission: 'Automatic',
        seatingCapacity: 5,
        color: 'Silver',
        features: 'Luxurious, Smooth ride',
    },
    6: {
        manufacturer: 'Tesla',
        model: 'Model S',
        year: 2021,
        fuelType: 'Electric',
        engineCapacity: 'N/A',
        transmission: 'Automatic',
        seatingCapacity: 5,
        color: 'Red',
        features: 'Electric, High-tech features',
    },
};
var CarDetails = function () {
    var id = useParams().id;
    var carId = Number(id);
    var car = carDetails[carId];
    if (!car) {
        return React.createElement("div", null, "Car details not found!");
    }
    return (React.createElement("div", null,
        React.createElement("h2", null,
            car.manufacturer,
            " ",
            car.model),
        React.createElement("p", null,
            React.createElement("strong", null, "Year:"),
            " ",
            car.year),
        React.createElement("p", null,
            React.createElement("strong", null, "Fuel Type:"),
            " ",
            car.fuelType),
        React.createElement("p", null,
            React.createElement("strong", null, "Engine Capacity:"),
            " ",
            car.engineCapacity),
        React.createElement("p", null,
            React.createElement("strong", null, "Transmission:"),
            " ",
            car.transmission),
        React.createElement("p", null,
            React.createElement("strong", null, "Seating Capacity:"),
            " ",
            car.seatingCapacity),
        React.createElement("p", null,
            React.createElement("strong", null, "Color:"),
            " ",
            car.color),
        React.createElement("p", null,
            React.createElement("strong", null, "Features:"),
            " ",
            car.features)));
};
export default CarDetails;
